### ISSUE TITLE
Pitchbend

### ISSUE THREAD

**Issue by marlow77** [max22-/ESP32-BLE-MIDI#23]
Hello!

Thank you for making this library and the examples are great!

I can't explain the feeling of accomplishment I got just from making it okay the midi key over to my Android phone, super cool!

Can you help me figure out how I would send pitchbend messages?  I tried multiple ways with the header information files, but I couldn't get it to work.

Thanks in advance,

Marlow

**Comment by max22-** [comment]
Hello, I've replied by mail but i don't see it here so i post it here just in case :

 ```
Hello,

thank you for your message !

for the pitch bend you should use this function :

https://github.com/max22-/ESP32-BLE-MIDI/blob/master/src/utility/Midi.h#L21

for example, if you want to simulate a modulation wheel with a potentiometer connected to pin 39 you could do something like this in your main loop :

float semitones = (float)analogRead(39) / 4096.0 * 4 - 2;

BLEMidiServer.pitchBend(0, semitones);

In general pitchbend goes from -2 to +2 semitones, but if your android app doesn't have the same range, you can provide it as a third argument.

I hope this can be helpful for you.

Maxime
```

**Comment by marlow77** [comment]
Thank you for getting back to me so quickly!  I'll report back how it goes.  Thanks!MarlowOn 20 Jun 2023 00:01, Maxime ANDRÉ ***@***.***> wrote:
Hello, I've replied by mail but i don't see it here so i post it here just in case :
Hello,

thank you for your message !

for the pitch bend you should use this function :

https://github.com/max22-/ESP32-BLE-MIDI/blob/master/src/utility/Midi.h#L21

for example, if you want to simulate a modulation wheel with a potentiometer connected to pin 39 you could do something like this in your main loop :

float semitones = (float)analogRead(39) / 4096.0 * 4 - 2;

BLEMidiServer.pitchBend(0, semitones);

In general pitchbend goes from -2 to +2 semitones, but if your android app doesn't have the same range, you can provide it as a third argument.

I hope this can be helpful for you.

Maxime
