### ISSUE TITLE
ble connect and disconnect problem

### ISSUE THREAD

**Issue by anukul1392001** [max22-/ESP32-BLE-MIDI#6]
Even after the newer update, the code gets stuck and the ble device doesn't show up.
Had to reset the board every time, I encounter this bug

**Comment by max22-** [comment]
Can you show me your code ?

**Comment by anukul1392001** [comment]
got them working xD.
Sorry to trouble you max :)

**Comment by max22-** [comment]
No problem ;)

**Comment by anukul1392001** [comment]
> No problem ;)

Dude can you please share me your Email. If in case I need it for help pliz xD :)
